name: ci

env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.py"
      - "**.nml"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python: [true, false]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build -Dfind:BOOL=true -Dmsis2:BOOL=true --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target ffilesystem glow hwm14 msis mumps
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: Configure
      run: cmake --preset default -Dpython:BOOL=${{ matrix.python }} -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs

    - name: build
      run: cmake --build build

    - name: Run Bounds check
      run: ctest --preset default -R run_bounds_check -E 3D


  linux-matlab:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build -Dfind:BOOL=true -Dmsis2:BOOL=true --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target ffilesystem glow hwm14 msis mumps
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: Configure with Matlab
      run: cmake --preset matlab -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs

    - name: build
      run: cmake --build build

    - name: Run Bounds check
      run: ctest --preset default -R run_bounds_check -E 3D
