name: ci

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_PREFIX_PATH: ~/gemlibs

on:
  push:
    paths:
      - "**.py"
      - "**.nml"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python: [true, false]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -S gemext -B gemext/build -Dfind:BOOL=true -Dmsis2:BOOL=true -DCMAKE_INSTALL_PREFIX:PATH=${{ env.CMAKE_PREFIX_PATH }}
        cmake --build gemext/build --target ffilesystem glow hwm14 msis mumps
        cmake --install gemext/build

    - name: Checkout PyGemini
      if: ${{ matrix.python }}
      uses: actions/checkout@v2
      with:
        repository: gemini3d/pygemini
        path: pygemini

    - name: install PyGemini
      if: ${{ matrix.python }}
      run: python -m pip install -e ${{ github.workspace }}/pygemini

    - name: Configure Python=${{ matrix.python }}
      run: cmake --preset default -Dpython:BOOL=${{ matrix.python }}

    - name: build Gemini3D
      run: cmake --build build

    - name: Run Bounds check
      run: ctest --preset default -R run_bounds_check -E 3D


  linux-matlab:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -S gemext -B gemext/build -Dfind:BOOL=true -Dmsis2:BOOL=true -DCMAKE_INSTALL_PREFIX:PATH=${{ env.CMAKE_PREFIX_PATH }}
        cmake --build gemext/build --target ffilesystem glow hwm14 msis mumps
        cmake --install gemext/build

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Configure with Matlab
      run: cmake --preset matlab

    - name: build Gemini3D
      run: cmake --build build

    - name: Run Bounds check
      run: ctest --preset default -R run_bounds_check -E 3D
