name: ci

on:
  push:
    paths:
      - "**.py"
      - "**.nml"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"
# paths ignore starting with "!"
      - "!ci.cmake"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        cpp: [true, false]
        python: [true, false]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v3
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install Prereqs
      run: |
        sudo apt update
        sudo $(cmake -P gemext/scripts/requirements.cmake) libmumps-dev

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -S gemext -B gemext/build -Dfind:BOOL=true -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}
        cmake --build gemext/build --target ffilesystem glow iniparser msis mumps
        cmake --install gemext/build

    - name: Checkout PyGemini
      if: ${{ matrix.python }}
      uses: actions/checkout@v3
      with:
        repository: gemini3d/pygemini
        path: pygemini

    - name: install PyGemini
      if: ${{ matrix.python }}
      run: python -m pip install -e ./pygemini

    - name: Configure C++=${{ matrix.cpp }} Python=${{ matrix.python }}
      run: >-
        cmake --preset default
        -Dcpp:BOOL=${{ matrix.cpp }}
        -Dpython:BOOL=${{ matrix.python }}
        -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }}

    - name: build Gemini3D
      run: cmake --build build

    - name: Run Bounds check
      run: ctest --preset default -R run_bounds_check -E 3D
      env:
        CMAKE_PREFIX_PATH: ${{ runner.temp }}


  linux-matlab:
    if: false
    # NOTE: This fails numeric comparision checks. This is probably an issue that needs to be fixed in MatGemini to match PyGemini.
    # For now, disabling MatGemini CI sims.
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v3
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install Prereqs
      run: |
        sudo apt update
        sudo $(cmake -P gemext/scripts/requirements.cmake) libmumps-dev

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -S gemext -B gemext/build -Dfind:BOOL=true -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}
        cmake --build gemext/build --target ffilesystem glow iniparser msis mumps
        cmake --install gemext/build

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Checkout MatGemini
      uses: actions/checkout@v3
      with:
        repository: gemini3d/mat_gemini
        path: mat_gemini

    - name: Configure with Matlab
      run: cmake --preset matlab
      env:
        MATGEMINI: ${{ github.workspace }}/mat_gemini

    - name: build Gemini3D
      run: cmake --build build

    - name: Run Bounds check
      run: ctest --preset default -R run_bounds_check -E 3D
