name: ci

on:
  push:
    paths:
      - "**.py"
      - "**.nml"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "cmake/libraries.json"
      - ".github/workflows/ci.yml"
# paths ignore starting with "!"
      - "!ci.cmake"

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


env:
  CTEST_NO_TESTS_ACTION: error
  HOMEBREW_NO_INSTALL_CLEANUP: 1


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          # - gen: matlab
          #   cpp: false
          # TODO: tolerance/shape issues to work through in Matlab--despite MatGemini self-compare CI working
          - gen: python
            pyversion: '3.10'
          # use whatever Python version you like; the minimum Python version is set in pygemini/pyproject.toml
          - gen: none

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-pkg

# --- Python
    - name: Setup Python ${{ matrix.pyversion }}
      if: ${{ matrix.gen == 'python' }}
      uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.pyversion }}'

    - name: Checkout PyGemini
      if: ${{ matrix.gen == 'python' }}
      uses: actions/checkout@v4
      with:
        repository: gemini3d/pygemini
        path: pygemini

    - name: install PyGemini
      if: ${{ matrix.gen == 'python' }}
      run: python -m pip install -e ./pygemini

    - name: Configure Python=${{ matrix.pyversion }}
      if: ${{ matrix.gen != 'matlab' }}
      run: >-
        cmake --preset default
        -Dpython:BOOL=${{ matrix.gen == 'python' }}

# --- Matlab

    - name: Install MATLAB
      if: ${{ matrix.gen == 'matlab' }}
      uses: matlab-actions/setup-matlab@v2
      with:
        release: latest
        cache: true

    - name: Checkout MatGemini
      if: ${{ matrix.gen == 'matlab' }}
      uses: actions/checkout@v4
      with:
        repository: gemini3d/mat_gemini
        path: mat_gemini
        submodules: true

    - name: Configure with Matlab
      if: ${{ matrix.gen == 'matlab' }}
      run: cmake --preset matlab
      env:
        MATGEMINI: ${{ github.workspace }}/mat_gemini

# --- build

    - name: build Gemini3D
      run: cmake --build build

    - name: Run Bounds check
      run: ctest --preset default -R run_bounds_check -E 3D
